SONAR_BLOCKER=0
SONAR_CRITICAL=0
SONAR_MAJOR=0
SONAR_MINOR=0
SONAR_COVERAGE=83
SONAR_DUPLICATIONS=0

SONAR_NEW_COVERAGE=45
SONAR_NEW_BLOCKER=0
SONAR_NEW_CRITICAL=0
SONAR_NEW_BUGS=0
SONAR_NEW_MAJOR=0
SONAR_NEW_MINOR=0
SONAR_NEW_VIOLATIONS=0

SONAR_RELIABILITY_RATING=A
SONAR_SECURITY_RATING=A
SONAR_MAINTAINABILITY_RATING=A
SONAR_CODE_COVERAGE=45
SONAR_QG=OK

MUTATION_COVERAGE=84
MUTATION_TEST_STRENGTH=90

VERACODE_VERYHIGH=0
VERACODE_HIGH=0
VERACODE_MEDIUM=2
VERACODE_LOW=2
VERACODE_RATING=B
VERACODE_SCORE=99

SCA_CRITICAL=0
SCA_HIGH=11
SCA_MEDIUM=6
SCA_LOW=0

SKIP_CONNECTION_ERROR=true

